export const FETCH_EVENTS_START = 'FETCH_EVENT_START';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENTS_FAILED = 'FETCH_EVENT_FAILED';
export const SET_EVENT_LISTS = 'SET_EVENT_LISTS';
export const SET_SELECTED_EVENT = 'SET_SELECTED_EVENT';
export const SET_BOOKING_DATA = 'SET_BOOKING_DATA';
export const CLEAR_BOOKING_DATA = 'CLEAR_BOOKING_DATA';
